2024-08-01 11:43:18,183 - my_application - ERROR - Some error occurred
Traceback (most recent call last):
  File "C:/Users/miche/Downloads/login_test.py", line 22, in <module>
    raise ValueError("Some error occurred")
ValueError: Some error occurred
2024-08-01 13:26:35,146 - my_application - ERROR - Some error occurred
Traceback (most recent call last):
  File "C:/Users/miche/Downloads/login_test.py", line 22, in <module>
    raise ValueError("Some error occurred")
ValueError: Some error occurred
